apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
  labels:
    app: library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
      - name: library
        image: 644435390668.dkr.ecr.eu-central-1.amazonaws.com/library:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: clusterip-library
  labels:
    app: library
spec:
  type: ClusterIP
  selector:
    app: library
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 5000