apiVersion: v1
kind: Service
metadata:
  external-dns.alpha.kubernetes.io/hostname: marcinlib.click
  name: {{ include "library.fullname" . }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "library.selectorLabels" . | nindent 4 }}
