apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-menager
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/cert-menager
    repoURL: https://github.com/Tuzinkowy/lib-argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true