kibana:
  replicas: 3
  files:
    kibana.yml:
      server.name: efk-logging-kibana
      server.host: "0"
      elasticsearch.hosts: http://elasticsearch-master:9200
  service:
    type: LoadBalancer
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"