apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: clusterip-demo-crm 
            port: 
              number: 3000