apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: argo
spec:
  rules:
  - host: a2d388db44a1247b9828b81e560bd084-1340101577.eu-central-1.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: argo-cd-argocd-server
            port: 
              number: 443