apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: clusterip-library
            port: 
              number: 80