apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - batcow.ddns.net
    secretName: portfolio-app-tls
  rules:
  - host: batcow.ddns.net
    http: 
        paths:
        - path: /
          pathType: Prefix
          backend:
            service: 
              name: library
              port: 
                number: 80