kube-prometheus-stack:
  defaultRules:
    rules:
      etcd: false
      kubeSchedulerAlerting: false
      kubeSchedulerRecording: false
      nodeExporterAlerting: false
      nodeExporterRecording: false
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  nodeExporter:
    enabled: false
  grafana:
    adminPassword: SecretPassword
    service:
      type: LoadBalancer