elasticsearch:

  minimumMasterNodes: 1
  replicas: 1

  # Allocate smaller chunks of memory per pod.
  resources:
    requests:
      cpu: "100m"
      memory: "512M"
    limits:
      cpu: "1000m"
      memory: "512M"

  # Shrink default JVM heap.
  esJavaOpts: "-Xmx128m -Xms128m"

  antiAffinity: "soft"

  # Request smaller persistent volumes.
  #volumeClaimTemplate:
  #  accessModes: [ "ReadWriteOnce" ]
  #  storageClassName: "standard"
  #  resources:
  #    requests:
  #      storage: 100M